### ISSUE TITLE
bthread::id_create_impl发生coredump

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-brpc#1178]
**Describe the bug (描述bug)**
[Apache Doris](https://github.com/apache/incubator-doris) 使用了brpc，发现有多次coredump发生在如下栈：
```
Core was generated by `/home/work/app/doris/c3prc-bigbi/be/package/be/lib/palo_be'.
Program terminated with signal 11, Segmentation fault.
#0  bthread::id_create_impl (id=id@entry=0x7f6c0fc26200, data=data@entry=0x1a5c2508, on_error=on_error@entry=0x0,
    on_error2=on_error2@entry=0x1b9fea0 <brpc::Controller::HandleSocketFailed(bthread_id_t, void*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)
    at /root/doris/doris-dev/thirdparty/src/incubator-brpc-0.9.5/src/bthread/id.cpp:333
333	/root/doris/doris-dev/thirdparty/src/incubator-brpc-0.9.5/src/bthread/id.cpp: 没有那个文件或目录.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-157.el7_3.1.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb)
(gdb) bt
#0  bthread::id_create_impl (id=id@entry=0x7f6c0fc26200, data=data@entry=0x1a5c2508, on_error=on_error@entry=0x0,
    on_error2=on_error2@entry=0x1b9fea0 <brpc::Controller::HandleSocketFailed(bthread_id_t, void*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)
    at /root/doris/doris-dev/thirdparty/src/incubator-brpc-0.9.5/src/bthread/id.cpp:333
#1  0x0000000001d1387d in bthread_id_create2 (id=id@entry=0x7f6c0fc26200, data=data@entry=0x1a5c2508,
    on_error=on_error@entry=0x1b9fea0 <brpc::Controller::HandleSocketFailed(bthread_id_t, void*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)
    at /root/doris/doris-dev/thirdparty/src/incubator-brpc-0.9.5/src/bthread/id.cpp:693
#2  0x0000000001b9a86d in brpc::Controller::call_id (this=this@entry=0x1a5c2508) at /root/doris/doris-dev/thirdparty/src/incubator-brpc-0.9.5/src/brpc/controller.cpp:1213
#3  0x0000000001b9634d in brpc::Channel::CallMethod (this=0xd406a00, method=0x5215dc00, controller_base=0x1a5c2508, request=0x15dd94aa0, response=0x1a5c2758, done=0x1a5c2500) at /root/doris/doris-dev/thirdparty/src/incubator-brpc-0.9.5/src/brpc/channel.cpp:394
#4  0x00000000013659bf in palo::PInternalService_Stub::transmit_data (this=<optimized out>, controller=0x1a5c2508, request=0x15dd94aa0, response=0x1a5c2758, done=0x1a5c2500) at /builds/olap/doris/gensrc/build/gen_cpp/palo_internal_service.pb.cc:319
#5  0x00000000015fb4a1 in doris::DataStreamSender::Channel::send_batch (this=this@entry=0x15dd949a0, batch=batch@entry=0x15dd94a58, eos=eos@entry=true) at /builds/olap/doris/be/src/runtime/data_stream_sender.cpp:232
#6  0x00000000015fb774 in doris::DataStreamSender::Channel::send_current_batch (this=this@entry=0x15dd949a0, eos=eos@entry=true) at /builds/olap/doris/be/src/runtime/data_stream_sender.cpp:275
#7  0x00000000015fc071 in doris::DataStreamSender::Channel::close_internal (this=0x15dd949a0) at /builds/olap/doris/be/src/runtime/data_stream_sender.cpp:287
#8  0x00000000015fc215 in close (state=0x153800000, this=<optimized out>) at /builds/olap/doris/be/src/runtime/data_stream_sender.cpp:296
#9  doris::DataStreamSender::close (this=0x59a38680, state=0x153800000, exec_status=...) at /builds/olap/doris/be/src/runtime/data_stream_sender.cpp:607
#10 0x00000000010208d3 in doris::PlanFragmentExecutor::open_internal (this=this@entry=0x2e998e30) at /builds/olap/doris/be/src/runtime/plan_fragment_executor.cpp:326
#11 0x0000000001020acc in doris::PlanFragmentExecutor::open (this=this@entry=0x2e998e30) at /builds/olap/doris/be/src/runtime/plan_fragment_executor.cpp:259
#12 0x0000000000fb1267 in doris::FragmentExecState::execute (this=0x2e998dc0) at /builds/olap/doris/be/src/runtime/fragment_mgr.cpp:211
#13 0x0000000000fb2d16 in doris::FragmentMgr::exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) (this=0x6435c00, exec_state=..., cb=...) at /builds/olap/doris/be/src/runtime/fragment_mgr.cpp:394
#14 0x0000000000fb96b8 in __invoke_impl<void, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void(doris::PlanFragmentExecutor*)>&> (__t=@0xbc1f32b0: 0x6435c00, __f=
    @0xbc1f3270: (void (doris::FragmentMgr::*)(doris::FragmentMgr * const, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)) 0xfb2cf0 <doris::FragmentMgr::exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>) at /usr/include/c++/7.3.0/bits/invoke.h:73
#15 __invoke<void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void(doris::PlanFragmentExecutor*)>&> (__fn=
    @0xbc1f3270: (void (doris::FragmentMgr::*)(doris::FragmentMgr * const, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)) 0xfb2cf0 <doris::FragmentMgr::exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>) at /usr/include/c++/7.3.0/bits/invoke.h:95
#16 __call<void, 0, 1, 2> (__args=..., this=0xbc1f3270) at /usr/include/c++/7.3.0/functional:632
#17 operator()<> (this=0xbc1f3270) at /usr/include/c++/7.3.0/functional:718
#18 boost::detail::function::void_function_obj_invoker0<std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>, void>::invoke(boost::detail::function::function_buffer&) (function_obj_ptr=...) at /var/local/thirdparty/installed/include/boost/function/function_template.hpp:159
#19 0x0000000000fb24d4 in operator() (this=0x1c9db9180) at /var/local/thirdparty/installed/include/boost/function/function_template.hpp:759
#20 doris::fragment_executor (param=0x1c9db9180) at /builds/olap/doris/be/src/runtime/fragment_mgr.cpp:419
#21 0x00007f6de8798dc5 in start_thread () from /lib64/libpthread.so.0
#22 0x00007f6de8aa473d in clone () from /lib64/libc.so.6
(gdb) f 0
#0  bthread::id_create_impl (id=id@entry=0x7f6c0fc26200, data=data@entry=0x1a5c2508, on_error=on_error@entry=0x0,
    on_error2=on_error2@entry=0x1b9fea0 <brpc::Controller::HandleSocketFailed(bthread_id_t, void*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)
    at /root/doris/doris-dev/thirdparty/src/incubator-brpc-0.9.5/src/bthread/id.cpp:333
333	in /root/doris/doris-dev/thirdparty/src/incubator-brpc-0.9.5/src/bthread/id.cpp
(gdb) p butex
$1 = (uint32_t *) 0x0
(gdb)
```
其中，`bthread::id_create_impl`函数中，`get_resource`申请到的`Id`的`butex`字段为0。

**To Reproduce (复现方法)**
没有必现的方法。

**Expected behavior (期望行为)**
应正常运行

**Versions (各种版本)**
OS:
Compiler:
brpc: 0.9.5
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
same as #1188
