### ISSUE TITLE
如果用bazel编译brpc的话，bazel需要到多少版本呢？

### ISSUE THREAD

**Issue by whutbd** [apache/incubator-brpc#1268]
如果用bazel编译braft的话，bazel需要到多少版本呢？

**Comment by yanglimingcn** [comment]
这个有答案了吗？

**Comment by pcman-zhang** [comment]
目前我用bazel 3.6编译不过

**Comment by tanzhongyi003** [comment]
bazel 出4.0版本了，4.0是LTS版本，维护期两年。
用4.0试试，
如果build不过，看看啥原因

**Comment by hiberabyss** [comment]
用 bazel 4 也编译不了，protobu 现在会有问题

**Comment by wwbmmm** [comment]
master has support latest version of bazel

**Comment by NKcqx** [comment]
protobuf 仍然有问题
bazel version: 4.2.2
brpc master commit: 5283d0d930c33e03346ab59de3580c061c3e90b8
报错：
```
INFO: Repository com_google_protobuf instantiated at:
  /Users/paer/Documents/work/Code/incubator-brpc/WORKSPACE:236:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_paer/ce07402dfb742d9a250bfd2335df0ebb/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository 'com_google_protobuf' used the following cache hits instead of downloading the corresponding file.
 * Hash '87407cd28e7a9c95d9f61a098a53cf031109d451a7763e7dd1253abf8b4df422' for https://github.com/protocolbuffers/protobuf/archive/refs/tags/v3.19.1.tar.gz
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_paer/ce07402dfb742d9a250bfd2335df0ebb/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, column 10, in _http_archive_impl
                patch(ctx)
        File "/private/var/tmp/_bazel_paer/ce07402dfb742d9a250bfd2335df0ebb/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 161, column 21, in patch
                fail("Error applying patch command %s:\n%s%s" %
Error in fail: Error applying patch command sed -i protobuf.bzl -re '4,4d;417,508d':
sed: -I or -i may not be used with stdin
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/private/var/tmp/_bazel_paer/ce07402dfb742d9a250bfd2335df0ebb/external/bazel_tools/tools/build_defs/repo/http.bzl", line 121, column 10, in _http_archive_impl
                patch(ctx)
        File "/private/var/tmp/_bazel_paer/ce07402dfb742d9a250bfd2335df0ebb/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 161, column 21, in patch
                fail("Error applying patch command %s:\n%s%s" %
Error in fail: Error applying patch command sed -i protobuf.bzl -re '4,4d;417,508d':
sed: -I or -i may not be used with stdin
INFO: Repository openssl instantiated at:
  /Users/paer/Documents/work/Code/incubator-brpc/WORKSPACE:256:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_paer/ce07402dfb742d9a250bfd2335df0ebb/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /Users/paer/Documents/work/Code/incubator-brpc/BUILD.bazel:295:11: //:butil depends on @com_google_protobuf//:protobuf in repository @com_google_protobuf which failed to fetch. no such package '@com_google_protobuf//': Error applying patch command sed -i protobuf.bzl -re '4,4d;417,508d':
sed: -I or -i may not be used with stdin
ERROR: Analysis of target '//:brpc' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.990s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @local_config_xcode; fetching
```
