### ISSUE TITLE
使用bvar的dumpserver时 core

### ISSUE THREAD

**Issue by UncleWangNearBy** [apache/incubator-brpc#1591]
**Describe the bug (描述bug)**
在使用端口时core，

代码:
```
  if (google::SetCommandLineOption("bvar_dump", "true").empty()) {
        MV_ERROR((L_ERROR,"Fail to enable bvar dump"));
  }

  brpc::StartDummyServerAt(8887);
```

在浏览器输入8887/vars 时候core了

对应的core内容
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./bin/dspserver only_open_bool_engine=false --zk_hosts=dsp01.adsys.shbt.qihoo.n'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00000035e6632925 in raise () from /lib64/libc.so.6
(gdb) bt
#1  0x00000035e6634105 in abort () from /lib64/libc.so.6
#2  0x00000035e6670837 in __libc_message () from /lib64/libc.so.6
#3  0x00000035e6676166 in malloc_printerr () from /lib64/libc.so.6
#4  0x00000035e6679bf4 in _int_malloc () from /lib64/libc.so.6
#5  0x00000035e667a9a1 in malloc () from /lib64/libc.so.6
#6  0x0000000000c6de86 in create_block (block_size=8192) at /home/winkmiao/incubator-brpc/src/butil/iobuf.cpp:301
#7  create_block () at /home/winkmiao/incubator-brpc/src/butil/iobuf.cpp:310
#8  butil::iobuf::acquire_tls_block () at /home/winkmiao/incubator-brpc/src/butil/iobuf.cpp:462
#9  0x0000000000c722b6 in butil::IOBufAsZeroCopyOutputStream::Next (this=0x7fac3bdfcf80, data=0x7fac3bdfcfc0,
    size=0x7fac3bdfcfc8) at /home/winkmiao/incubator-brpc/src/butil/iobuf.cpp:1930
#10 0x0000000001197730 in google::protobuf::io::GzipOutputStream::Deflate (this=0x7fac3bdfcfb0, flush=4)
    at google/protobuf/io/gzip_stream.cc:258
#11 0x0000000001197844 in google::protobuf::io::GzipOutputStream::Close (this=this@entry=0x7fac3bdfcfb0)
    at google/protobuf/io/gzip_stream.cc:323
#12 0x0000000000df0888 in brpc::policy::GzipCompress (msg=..., buf=buf@entry=0x7fac3bdfd150, options_in=options_in@entry=0x0)
    at /home/winkmiao/incubator-brpc/src/brpc/policy/gzip_compress.cpp:102
#13 0x0000000000de045a in brpc::policy::HttpResponseSender::~HttpResponseSender (this=0x7fac2802c208, __in_chrg=<optimized out>)
    at /home/winkmiao/incubator-brpc/src/brpc/policy/http_rpc_protocol.cpp:848
#14 0x0000000000de3614 in ~HttpResponseSenderAsDone (this=0x7fac2802c200, __in_chrg=<optimized out>)
    at /home/winkmiao/incubator-brpc/src/brpc/policy/http_rpc_protocol.cpp:698
#15 brpc::policy::HttpResponseSenderAsDone::~HttpResponseSenderAsDone (this=0x7fac2802c200, __in_chrg=<optimized out>)
    at /home/winkmiao/incubator-brpc/src/brpc/policy/http_rpc_protocol.cpp:698
#16 0x0000000000cc8a5b in ~ClosureGuard (this=<synthetic pointer>, __in_chrg=<optimized out>)
    at /home/winkmiao/incubator-brpc/src/brpc/closure_guard.h:39
#17 brpc::StatusService::default_method (this=<optimized out>, cntl_base=0x7fac2802b7b0, done=0x7fac2802c200)
    at /home/winkmiao/incubator-brpc/src/brpc/builtin/status_service.cpp:234
#18 0x0000000000cd6743 in brpc::IndexService::default_method (this=<optimized out>, controller=0x7fac2802b7b0,
    done=0x7fac2802c200) at /home/winkmiao/incubator-brpc/src/brpc/builtin/index_service.cpp:63
#19 0x0000000000d4c49e in brpc::index::CallMethod (this=0x8607ea0, method=<optimized out>, controller=0x7fac2802b7b0, request=
    0x7fac2801af90, response=0x7fac2802ba80, done=0x7fac2802c200)
    at /home/winkmiao/incubator-brpc/build/brpc/builtin_service.pb.cc:7468
#20 0x0000000000de18f7 in brpc::policy::ProcessHttpRequest (msg=<optimized out>)
    at /home/winkmiao/incubator-brpc/src/brpc/policy/http_rpc_protocol.cpp:1499
#21 0x0000000000d342ca in brpc::ProcessInputMessage (void_arg=void_arg@entry=0x7fac28023de0)
    at /home/winkmiao/incubator-brpc/src/brpc/input_messenger.cpp:135
#22 0x0000000000d351c8 in operator() (this=<optimized out>, last_msg=0x7fac28023de0)
    at /home/winkmiao/incubator-brpc/src/brpc/input_messenger.cpp:141
#23 brpc::InputMessenger::OnNewMessages (m=0x7fac1001ac80) at /usr/local/gcc4.9.2/include/c++/4.9.2/bits/unique_ptr.h:236
#24 0x0000000000d1526d in brpc::Socket::ProcessEvent (arg=0x7fac1001ac80)
    at /home/winkmiao/incubator-brpc/src/brpc/socket.cpp:1018
#25 0x0000000000d96411 in bthread::TaskGroup::task_runner (skip_remained=<optimized out>)
    at /home/winkmiao/incubator-brpc/src/bthread/task_group.cpp:295
#26 0x0000000000da78a1 in bthread_make_fcontext ()
Backtrace stopped: Cannot access memory at address 0x7fac3bdfe000
**To Reproduce (复现方法)**
我本机 稳定复现

**Versions (各种版本)**
OS: 2.6.32-220.7.1.el6.2.0.0.9.x86_64
Compiler: gcc 4.9.2
brpc:最新master
protobuf: 2.4.1

**Additional context/screenshots (更多上下文/截图)**

**Comment by UncleWangNearBy** [comment]
描述的有问题
