### ISSUE TITLE
gdb调试brpc服务出core

### ISSUE THREAD

**Issue by Lowpower** [apache/incubator-brpc#1705]
**Versions (各种版本)**
OS: linux 3.10.0-957.el7.x86_64 
Compiler: gcc version 5.2.0 (GCC) 

堆栈信息:
Program terminated with signal 5, Trace/breakpoint trap.
#0  0x0000000000517a96 in bvar::detail::PercentileSamples<254ul>::~PercentileSamples (this=0x7fa087390528, __in_chrg=<optimized out>) at external/com_github_brpc_brpc/src/bvar/detail/percentile.h:249
249	external/com_github_brpc_brpc/src/bvar/detail/percentile.h: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-324.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64
(gdb) bt
#0  0x0000000000517a96 in bvar::detail::PercentileSamples<254ul>::~PercentileSamples (this=0x7fa087390528, __in_chrg=<optimized out>) at external/com_github_brpc_brpc/src/bvar/detail/percentile.h:249
#1  0x0000000002ba622b in std::_Destroy<bvar::detail::PercentileSamples<254ul> > (__pointer=0x7fa087390528) at /usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/../../../../include/c++/5.2.0/bits/stl_construct.h:93
#2  0x0000000002ba57db in std::_Destroy_aux<false>::__destroy<bvar::detail::PercentileSamples<254ul>*> (__first=0x7fa087390528, __last=0x7fa087390948) at /usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/../../../../include/c++/5.2.0/bits/stl_construct.h:103
#3  0x0000000002ba4944 in std::_Destroy<bvar::detail::PercentileSamples<254ul>*> (__first=0x7fa087390000, __last=0x7fa087390948) at /usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/../../../../include/c++/5.2.0/bits/stl_construct.h:126
#4  0x0000000002ba2a39 in std::_Destroy<bvar::detail::PercentileSamples<254ul>*, bvar::detail::PercentileSamples<254ul> > (__first=0x7fa087390000, __last=0x7fa087390948) at /usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/../../../../include/c++/5.2.0/bits/stl_construct.h:151
#5  0x0000000002ba1555 in std::vector<bvar::detail::PercentileSamples<254ul>, std::allocator<bvar::detail::PercentileSamples<254ul> > >::~vector (this=0x7fa090044100, __in_chrg=<optimized out>) at /usr/local/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/../../../../include/c++/5.2.0/bits/stl_vector.h:424
#6  0x0000000002b9f059 in bvar::detail::combine (w=0x7f9c0ca21be0) at external/com_github_brpc_brpc/src/bvar/latency_recorder.cpp:107
#7  0x0000000002ba010e in bvar::LatencyRecorder::latency_percentile (this=0x7f9c0ca21940, ratio=0.98999999999999999) at external/com_github_brpc_brpc/src/bvar/latency_recorder.cpp:254
#8  0x0000000002b9f13a in bvar::detail::get_p3 (arg=0x7f9c0ca21940) at external/com_github_brpc_brpc/src/bvar/latency_recorder.cpp:129
#9  0x00000000005063a2 in bvar::PassiveStatus<long>::get_value (this=0x7f9c0ca21cb8) at external/com_github_brpc_brpc/src/bvar/passive_status.h:138
#10 0x000000000053a286 in bvar::PassiveStatus<long>::SeriesSampler::take_sample (this=0x7f9c0ca76a00) at external/com_github_brpc_brpc/src/bvar/passive_status.h:60
#11 0x0000000002ba8cf5 in bvar::detail::SamplerCollector::run (this=0x7fa09390e000) at external/com_github_brpc_brpc/src/bvar/detail/sampler.cpp:119
#12 0x0000000002ba9360 in bvar::detail::SamplerCollector::sampling_thread (arg=0x7fa09390e000) at external/com_github_brpc_brpc/src/bvar/detail/sampler.cpp:81
#13 0x00007fa093064ea5 in start_thread () from /lib64/libpthread.so.0
#14 0x00007fa091d829fd in clone () from /lib64/libc.so.6

**Comment by wwbmmm** [comment]
可能是这个问题：http://sourceware.org/gdb/wiki/FAQ#GDB_does_not_see_any_threads_besides_the_thread_in_which_crash_occurred.3B_or_SIGTRAP_kills_my_program_when_I_set_a_breakpoint.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/3894631/155949440-4f51925c-0cbe-4f33-a08d-3e9a169b9f82.png">

**Comment by lorinlee** [comment]
@Lowpower 请问问题是否解决哈
