### ISSUE TITLE
thrift模式下使用java客户端thrift原生api访问容易失败，服务端没有收到请求

### ISSUE THREAD

**Issue by zhaocc1106** [apache/incubator-brpc#2039]
**Describe the bug (描述bug)**
使用thrift模式搭建服务，java客户端使用thrift原生api访问，容易出现下面的错误：
```
Caused by: org.apache.thrift.transport.TTransportException
        at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:132) ~[libthrift-0.9.3.jar!/:0.9.3]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.9.3.jar!/:0.9.3]
        at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129) ~[libthrift-0.9.3.jar!/:0.9.3]
        at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101) ~[libthrift-0.9.3.jar!/:0.9.3]
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.9.3.jar!/:0.9.3]
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:429) ~[libthrift-0.9.3.jar!/:0.9.3]
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:318) ~[libthrift-0.9.3.jar!/:0.9.3]
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:219) ~[libthrift-0.9.3.jar!/:0.9.3]
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:77) ~[libthrift-0.9.3.jar!/:0.9.3]
        at com.rec.pctr.PredictService$Client.recv_Predict(PredictService.java:92) ~[classes!/:0.0.1-SNAPSHOT]
        at com.rec.pctr.PredictService$Client.Predict(PredictService.java:79) ~[classes!/:0.0.1-SNAPSHOT]
        ... 46 more
```
想问下有没有类似的问题，或者有没有比较好的调试方法呢？

**To Reproduce (复现方法)**
使用thrift模式搭建服务，java客户端使用thrift原生api访问

**Expected behavior (期望行为)**
访问没问题。

**Versions (各种版本)**
OS: SMP Debian 4.19.181-1 (2021-03-19) x86_64 x86_64 x86_64 GNU/Linux
Compiler: gcc g++
brpc: 1.3.0
protobuf: thrift

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
有TTransportException的报错具体信息吗

**Comment by zhaocc1106** [comment]
> 
直接触发了thrift jar的exception，看起来是read返回信息时抛出的，但是服务端没有收到这条信息。

**Comment by zhaocc1106** [comment]
> 有TTransportException的报错具体信息吗

直接触发了thrift jar的exception，看起来是read返回信息时抛出的，但是服务端没有收到这条信息。

**Comment by zhaocc1106** [comment]
问题已找到，服务端关闭了超时没有通信的链接，关闭问题。

**Comment by tiandikurong** [comment]
@zhaocc1106 我也遇到了此问题，请问怎么解决的？我的hive-2.3.9，hadoop-2.7.7

**Comment by zhaocc1106** [comment]
> @zhaocc1106 我也遇到了此问题，请问怎么解决的？我的hive-2.3.9，hadoop-2.7.7

试一下调大服务端参数idle_timeout_sec

**Comment by tiandikurong** [comment]
> > @zhaocc1106 我也遇到了此问题，请问怎么解决的？我的hive-2.3.9，hadoop-2.7.7
> 
> 试一下调大服务端参数idle_timeout_sec

可不可以参考一下你的代码？

**Comment by zhaocc1106** [comment]
> > > @zhaocc1106 我也遇到了此问题，请问怎么解决的？我的hive-2.3.9，hadoop-2.7.7
> > 
> > 
> > 试一下调大服务端参数idle_timeout_sec
> 
> 可不可以参考一下你的代码？

brpc::Server        server;
  brpc::ServerOptions options;
  server.set_version(PREDICTOR_VERSION);

  // Add predictor thrift service.
  options.thrift_service = new PredictServiceImpl();
  options.idle_timeout_sec = FLAGS_idle_timeout_sec;  // 调大
